export type Product = {
  slug: string;
  categorySlug: string;
  name: string;
  seoTitle: string;
  metaDescription: string;
  h1: string;
  shortDescription: string;
  overview: string;
  description: string;
  features: string[];
  benefits: string[];
  specifications: Array<{ label: string; value: string }>;
  applications: string[];
  industries: string[];
  faqs: Array<{ question: string; answer: string }>;
  ctaTitle: string;
  ctaText: string;
  datasheetLabel: string;
  image: string;
  keywords: string[];
};
